CREATE TABLE IF NOT EXISTS users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM('USER','ADMIN') DEFAULT 'USER',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS scans (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    risk_level ENUM('LOW','MEDIUM','HIGH') DEFAULT 'LOW',
    file_size INT,
    total_methods INT,
    dangerous_count INT DEFAULT 0,
    safe_count INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_scans_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS classes (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    scan_id BIGINT NOT NULL,
    class_name VARCHAR(255) NOT NULL,
    CONSTRAINT fk_classes_scan FOREIGN KEY (scan_id) REFERENCES scans(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS methods (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    class_id BIGINT NOT NULL,
    method_name VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL,
    risk_level ENUM('LOW','MEDIUM','HIGH') DEFAULT 'LOW',
    risk_reason TEXT,
    CONSTRAINT fk_methods_class FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS violations (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    scan_id BIGINT NOT NULL,
    method_name VARCHAR(255) NOT NULL,
    risk_level ENUM('LOW','MEDIUM','HIGH') DEFAULT 'LOW',
    reason VARCHAR(1000) NOT NULL,
    CONSTRAINT fk_violations_scan FOREIGN KEY (scan_id) REFERENCES scans(id) ON DELETE CASCADE
);

